name: CI-Code-Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  BLITZAR_BACKEND: cpu

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y clang lld
    - uses: taiki-e/install-action@cargo-llvm-cov
    - name: Clean Previous Coverage Artifacts
      run: cargo llvm-cov clean --workspace
    - name: Run Tests to Generate Coverage Data (All Features)
      run: cargo llvm-cov --no-report --all-features --workspace --exclude proof-of-sql-benches --ignore-filename-regex evm_tests
    #- name: Run Tests to Generate Coverage Data (Rayon Only)
    #  run: cargo llvm-cov --no-report --no-default-features --features="rayon"
    #- name: Run Tests to Generate Coverage Data (Blitzar Only)
    #  run: cargo llvm-cov --no-report --no-default-features --features="blitzar"
    #- name: Run Tests to Generate Coverage Data (std only)
    #  run: cargo llvm-cov --no-report --no-default-features --features="std"
    - name: Generate Final LCOV Report (Merged Coverage)
      run: cargo llvm-cov report --lcov --ignore-filename-regex '[/\\]evm_tests\.rs$' --output-path lcov.info
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: lcov.info
        fail_ci_if_error: true
    - name: Enforce Coverage Threshold
      run: cargo llvm-cov report --summary-only --fail-under-lines 94
